# Import Packages

In [27]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from dash import Dash, dcc, html, Input, Output
from urllib.request import urlopen
import json

In [28]:
%run preprocessing.ipynb

In [29]:
df2

,State,County,State code,County code,Year span,Measure name,Measure id,Numerator,Denominator,Raw value,fipscode,FIPS Code
0,US,United States,0,0,2003-2005,Violent crime rate,43,1328750.667,274877117.0,483.398066,0.0,00000
1,US,United States,0,0,2004-2006,Violent crime rate,43,1340928.667,277612778.5,483.021233,0.0,00000
2,US,United States,0,0,2005-2007,Violent crime rate,43,1355853.167,280407694.7,483.529230,0.0,00000
3,US,United States,0,0,2006-2008,Violent crime rate,43,1366928.333,287614567.7,475.263942,0.0,00000
4,US,United States,0,0,2007-2009,Violent crime rate,43,1339439.333,292576281.2,457.808585,0.0,00000
...,...,...,...,...,...,...,...,...,...,...,...,...
303478,WY,Weston County,56,45,2007,Daily fine particulate matter,125,NaN,NaN,9.370000,56045.0,56045
303479,WY,Weston County,56,45,2008,Daily fine particulate matter,125,NaN,NaN,7.450000,56045.0,56045
303480,WY,Weston County,56,45,2009,Daily fine particulate matter,125,NaN,NaN,12.770000,56045.0,56045
303481,WY,Weston County,56,45,2010,Daily fine particulate matter,125,NaN,NaN,12.110000,56045.0,56045
303482,WY,Weston County,56,45,2011,Daily fine particulate matter,125,NaN,NaN,10.710000,56045.0,56045

# Look at Violent Crime Rates in California

In [ ]:
# open counties location file
with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    counties = json.load(response)
# create animated map of violent crime rates across Year Spans
fig = px.choropleth(df2.loc[(df2['State'] == 'CA')&(df2['County']!= "California") & (df2['Measure name'] == "Violent crime rate")], 
                    geojson=counties, 
                    locations='FIPS Code', 
                    color='Raw value',
                           color_continuous_scale="turbo",
                           range_color=(0, 700),
                           scope="usa",
                            title='<b>Violent Crime Rates in California by County',
                           labels={'Raw value':'Violent Crime Rate',
                                  'fipscode':'FIPS Code'},
                            hover_name = 'County',
                    animation_frame="Year span"
                          )
fig.update_layout(margin={"r":0,"t":50,"l":0,"b":0},
                 height=600,
                 width=800)
# Adjust map geo options
fig.update_geos(showcountries=False, showcoastlines=True,
                fitbounds="locations",
                )
fig.show()